export const db = "main-stackoverflow-db"
export const questionCollection = "questions"
export const answerCollection = "answers"
export const commentCollection = "comments"
export const voteCollection = "votes"
export const questionAttachmentBucket = "questions-attachment"